<h1>check js  template</h1>

<div class="ok-di-em1">
    <button>xx ok di em 1</button>
</div>

<div class="ok-di-em2" data-mage-init='{"okdiem2":{"name":"Hien", "age":"30"}}'>
    <button>xx ok di em 2</button>
</div>

<canvas id="myChart" width="400" height="400"></canvas>

<script type="text/x-magento-init">
    {
        ".ok-di-em1": {
            "okdiem1":{"name":"Trung", "age":"27"}
        }
    }
</script>
<script>
    require([
        "jquery",
        "mage/calendar",
        "chartJs",
    ], function ($, jQuery, chartJs) {
        'use strict';
        console.log('checkjs');
        const ctx = document.getElementById('myChart').getContext('2d');
        const myChart = new chartJs(ctx, {
            type: 'bar',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    });
</script>
